# Production-specific configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
services:
  api:
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: always

  web:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: always