version: '3.8'
services:
  api:
    # Flask's dev server with the reloader instead of gunicorn
    command: ["python3", "main.py"]
    volumes:
      - ./data:/app/data
      - ./modules:/app/modules
      - ./core:/app/core
      - ./main.py:/app/main.py
      - ./shared.py:/app/shared.py
    environment:
      - IS_PROD=false
      - LOG_FORMAT=text
  bot:
    volumes:
      - ./data:/app/data
      - ./modules:/app/modules
      - ./core:/app/core
      - ./bot_main.py:/app/bot_main.py
      - ./shared.py:/app/shared.py
    environment:
      - IS_PROD=false
      - LOG_FORMAT=text
